spring:
  sharding:
    datasource:
      pg-a:
        jdbcUrl: ${datasource.a.url}
        username: ${datasource.a.username}
        password: ${datasource.a.password}
      pg-b:
        jdbcUrl: ${datasource.b.url}
        username: ${datasource.b.username}
        password: ${datasource.b.password}
    route:
      pg-a: A-N0-4
      pg-b: O-Z5-9