openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /products:
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            example:
              name: "New Product"
              price: 15.99
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: "c7d5f1e1-56af-4f70-b8ae-f63c1f5da4b4"
                name: "New Product"
                price: 15.99
  '/products/{id}':
    get:
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          description: ID of the product to get
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
                name: "Product 1"
                price: 10.99
        '404':
          description: Product not found
    delete:
      summary: Delete a product by ID
      parameters:
        - name: id
          in: path
          description: ID of the product to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      required:
        - name
        - price
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
        price:
          type: number
          format: double
