spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration
  config:
    import:
      - classpath:sharding-config-integration-test.yml
  flyway:
    enabled: false